In [16]:
#how we import numpy 
import numpy as np
arr=np.array([2,4,6,8,2])
arr

array([2, 4, 6, 8, 2])

In [15]:
#as list follows vector concept not multi-dimensional
ls=[[1,2,3,4],[3,4,5,6],[5,3,1,7]]
ls

[[1, 2, 3, 4], [3, 4, 5, 6], [5, 3, 1, 7]]

In [14]:
#how list coverts into multi dimensional list through arrays
np.array(ls)

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 3, 1, 7]])

In [11]:
#work as range fx like in loop
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [19]:
#generate 0's for vector
arr= np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [20]:
#0's for metrics
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [23]:
#linear space
arr=np.linspace(1,5,2)
arr

array([1., 5.])

In [24]:
arr=np.linspace(0,1)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [38]:
#random generation fx
#normalisation (0 and 1 k beech aye val)
np.random.rand(10)


array([0.25654457, 0.77619345, 0.40977827, 0.33353651, 0.86762446,
       0.56868986, 0.40407576, 0.31089505, 0.75238238, 0.00485377])

In [40]:
#standardaation(-3 se +3 tak aate hai)//ismei bs rand mei randn krna padhta
np.random.randn(10)

array([-0.69538587,  0.41976085,  1.12601751, -0.17210078, -0.27395052,
        0.52395355,  0.33984357, -2.15896019, -0.46645865, -0.69009248])

In [41]:
#6 , 0 se 6 tak no.dega
np.random.randint(6)


3

In [43]:
#shify+tab show recommandation
np.random.randint(10,20,4)  #low,high,size

array([11, 12, 19, 11], dtype=int32)

In [50]:
#Array Attributes
ab=np.array([[2,4,5,2],[2,3,4,5],[4,3,1,6],[4,5,7,3]])
ab.shape

(4, 4)

In [51]:
ab.size

16

In [52]:
ab.dtype

dtype('int64')

In [53]:
#Array Methods
#minimum and max
ab.min()


np.int64(1)

In [55]:
ab.max()

np.int64(7)

In [57]:
#sum
ab.sum()

np.int64(60)

In [60]:
#rows and columns dono ka sum
#row=1,column=0
colsum=np.sum(ab,axis=0)
colsum

array([12, 15, 17, 16])

In [61]:
ab.mean()

np.float64(3.75)

In [65]:
ab.std()

np.float64(1.5612494995995996)

In [64]:
ab.argmax()  #postion of highest element in array

np.int64(14)

In [67]:
ab.argmin()  #position of longest element in array

np.int64(10)

In [71]:
#Reshaping and resizing
abc=np.arange(1,16)
abc
#its an vector and want to create into metrics

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [75]:
d=abc.reshape(3,5)    #ismei 1 to 15 ka set bnana hoga row x column jitna like 1*15,3*5..)
d   #size 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])